In [1]:
from catboost import CatBoostClassifier

import pandas as pd
import numpy as np
import pycaret
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split  # For splitting data
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder  # For scaling
from sklearn.impute import SimpleImputer  # For handling missing values
from sklearn.preprocessing import OneHotEncoder, LabelEncoder  # For encoding categorical data
pd.set_option('display.max_rows', 500)

# Dataset Zidan

In [2]:
df_train = pd.read_csv("try out_TRAIN_zidan.csv")
df_test = pd.read_csv("try out_TEST_zidan(1).csv")

df_train

SK_ID_CURR  TARGET  NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  \
0           100002       1                   0            1             0   
1           100003       0                   0            0             0   
2           100004       0                   1            1             1   
3           100006       0                   0            0             0   
4           100007       0                   0            1             0   
...            ...     ...                 ...          ...           ...   
307506      456251       0                   0            1             0   
307507      456252       0                   0            0             0   
307508      456253       0                   0            0             0   
307509      456254       1                   0            0             0   
307510      456255       0                   0            0             0   

        FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                     1             0          202500.0    406597.5   
1                     0             0          270000.0   1293502.5   
2                     1             0           67500.0    135000.0   
3                     1             0          135000.0    312682.5   
4                     1             0          121500.0    513000.0   
...                 ...           ...               ...         ...   
307506                0             0          157500.0    254700.0   
307507                1             0           72000.0    269550.0   
307508                1             0          153000.0    677664.0   
307509                1             0          171000.0    370107.0   
307510                0             0          157500.0    675000.0   

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  \
0           24700.5  ...                 0                 0   
1           35698.5  ...                 0                 0   
2            6750.0  ...                 0                 0   
3           29686.5  ...                 0                 0   
4           21865.5  ...                 0                 0   
...             ...  ...               ...               ...   
307506      27558.0  ...                 0                 0   
307507      12001.5  ...                 0                 0   
307508      29979.0  ...                 0                 0   
307509      20205.0  ...                 0                 0   
307510      49117.5  ...                 0                 0   

        FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  \
0                      0                 0                         0.0   
1                      0                 0                         0.0   
2                      0                 0                         0.0   
3                      0                 0                         0.0   
4                      0                 0                         0.0   
...                  ...               ...                         ...   
307506                 0                 0                         0.0   
307507                 0                 0                         0.0   
307508                 0                 0                         1.0   
307509                 0                 0                         0.0   
307510                 0                 0                         0.0   

        AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                             0.0                         0.0   
1                             0.0                         0.0   
2                             0.0                         0.0   
3                             0.0                         0.0   
4                             0.0                         0.0   
...                           ...                         ...   
307506                        0.0                         0.0   
307507                        0.0                   

In [3]:
X = df_train.drop('TARGET', axis=1)
y = df_train['TARGET']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [66]:
# Initialize the CatBoostClassifier model
catboost = CatBoostClassifier(iterations=100, learning_rate=0.01, depth=3, random_state=42, verbose=1)

# Train the model
catboost.fit(X_resampled,y_resampled)

0:	learn: 0.6905414	total: 27.1ms	remaining: 2.68s
1:	learn: 0.6879501	total: 55.1ms	remaining: 2.7s
2:	learn: 0.6854611	total: 82.7ms	remaining: 2.67s
3:	learn: 0.6829697	total: 110ms	remaining: 2.64s
4:	learn: 0.6805580	total: 138ms	remaining: 2.61s
5:	learn: 0.6781657	total: 165ms	remaining: 2.59s
6:	learn: 0.6758251	total: 195ms	remaining: 2.59s
7:	learn: 0.6735430	total: 224ms	remaining: 2.58s
8:	learn: 0.6712754	total: 258ms	remaining: 2.61s
9:	learn: 0.6690524	total: 284ms	remaining: 2.56s
10:	learn: 0.6668671	total: 313ms	remaining: 2.53s
11:	learn: 0.6647010	total: 339ms	remaining: 2.49s
12:	learn: 0.6625563	total: 366ms	remaining: 2.45s
13:	learn: 0.6605067	total: 393ms	remaining: 2.42s
14:	learn: 0.6584150	total: 422ms	remaining: 2.39s
15:	learn: 0.6564226	total: 449ms	remaining: 2.36s
16:	learn: 0.6544325	total: 478ms	remaining: 2.33s
17:	learn: 0.6524708	total: 508ms	remaining: 2.31s
18:	learn: 0.6505929	total: 534ms	remaining: 2.28s
19:	learn: 0.6487446	total: 562ms	remai

In [7]:
catboost

In [67]:
# Melakukan prediksi pada data test
y_pred_catboost = catboost.predict(X_test)

In [68]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score


y_pred_proba = catboost.predict_proba(X_test)[:,1]
#y_pred_custom = (y_pred_proba <= 0.4).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(f"ROC AUC Score: {roc_auc}")

ROC AUC Score: 0.645149605082068


In [69]:
y_pred = catboost.predict(X_test)

In [70]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.7935710453148627
Precision: 0.14329127912330786
Recall: 0.31440695089917153
F1-Score: 0.19686234817813766
Confusion Matrix:
[[47251  9303]
 [ 3393  1556]]


In [71]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Create a DataFrame for organized display
metrics_df = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score'],
    'Value': [accuracy, precision, recall, f1]
})

# Print metrics
print(metrics_df.to_string(index=False))

# Print confusion matrix with formatting
print("\nConfusion Matrix:")
print(conf_matrix)


   Metric    Value
 Accuracy 0.793571
Precision 0.143291
   Recall 0.314407
 F1-Score 0.196862

Confusion Matrix:
[[47251  9303]
 [ 3393  1556]]


In [17]:
df_test

SK_ID_CURR  NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  \
0          100001                   0            0             0   
1          100005                   0            1             0   
2          100013                   0            1             1   
3          100028                   0            0             0   
4          100038                   0            1             1   
...           ...                 ...          ...           ...   
48739      456221                   0            0             0   
48740      456222                   0            0             0   
48741      456223                   0            0             1   
48742      456224                   0            1             0   
48743      456250                   0            0             1   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    1             0          135000.0    568800.0   
1                    1             0           99000.0    222768.0   
2                    1             0          202500.0    663264.0   
3                    1             2          315000.0   1575000.0   
4                    0             1          180000.0    625500.0   
...                ...           ...               ...         ...   
48739                1             0          121500.0    412560.0   
48740                0             2          157500.0    622413.0   
48741                1             1          202500.0    315000.0   
48742                0             0          225000.0    450000.0   
48743                0             0          135000.0    312768.0   

       AMT_ANNUITY  AMT_GOODS_PRICE  ...  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  \
0          20560.5         450000.0  ...                 0                 0   
1          17370.0         180000.0  ...                 0                 0   
2          69777.0         630000.0  ...                 0                 0   
3          49018.5        1575000.0  ...                 0                 0   
4          32067.0         625500.0  ...                 0                 0   
...            ...              ...  ...               ...               ...   
48739      17473.5         270000.0  ...                 0                 0   
48740      31909.5         495000.0  ...                 0                 0   
48741      33205.5         315000.0  ...                 0                 0   
48742      25128.0         450000.0  ...                 0                 0   
48743      24709.5         270000.0  ...                 0                 0   

       FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  \
0                     0                 0                         0.0   
1                     0                 0                         0.0   
2                     0                 0                         0.0   
3                     0                 0                         0.0   
4                     0                 0                         0.0   
...                 ...               ...                         ...   
48739                 0                 0                         0.0   
48740                 0                 0                         0.0   
48741                 0                 0                         0.0   
48742                 0                 0                         0.0   
48743                 0                 0                         0.0   

       AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                            0.0                         0.0   
1                            0.0                         0.0   
2                            0.0                         0.0   
3                            0.0                         0.0   
4                            0.0                         0.0   
...                          ...                         ...   
48739                        0.0                         0.0   

In [59]:
y_pred_test = catboost.predict(df_test)

In [60]:
y_pred_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
pred_df = pd.DataFrame(y_pred_test, columns=["TARGET"])
pred_df

TARGET
0           0
1           0
2           0
3           0
4           0
...       ...
48739       0
48740       0
48741       0
48742       0
48743       0

[48744 rows x 1 columns]

In [62]:
pred_df["TARGET"].nunique()

2

In [63]:
df_id_df = pd.DataFrame(df_test, columns=["SK_ID_CURR"])

In [50]:
df_id_df

SK_ID_CURR
0          100001
1          100005
2          100013
3          100028
4          100038
...           ...
48739      456221
48740      456222
48741      456223
48742      456224
48743      456250

[48744 rows x 1 columns]

In [64]:
final_sub = pd.concat([df_id_df, pred_df ], axis=1)
final_sub

SK_ID_CURR  TARGET
0          100001       0
1          100005       0
2          100013       0
3          100028       0
4          100038       0
...           ...     ...
48739      456221       0
48740      456222       0
48741      456223       0
48742      456224       0
48743      456250       0

[48744 rows x 2 columns]

In [65]:
final_sub.to_csv("submit_zidan_catboost4.csv", index=False)